baseurl = "https://RS-SiyuanWang.github.io"
title = "Siyuan's Blog"
theme = "hugo-theme-cleanwhite-rsy"
languageCode = "en-us"
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # header_image = "images/main_go_wideandtall_darklayer.jpeg"
  header_image = "Institute.jpg"
  title = "Idle folks lack no excuses."
  slogan = "Welcome to My Blog"
  # SEOTitle = " 思远的博客"
  keyword = "Siyuan, Wang, Remote Sensing, Vegetation Dynamic"
 
  # Sidebar settings
  sidebar_about_description = "Phd Candidate at Max Planck Institute"
  sidebar_avatar = "Avatar.jpg"
  about_me = true

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "/static/images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "swang@bgc-jena.mpg.de"
  github         = "https://github.com/RS-SiyuanWang"
